### ISSUE TITLE
Addition to start up instructions

### ISSUE THREAD

**Issue by dgreen** [johnbender/jqm-rails#1]
I think a "rake db:migrate" or a "bundle exec db:migrate" is needed at initial startup (in the instructions).

There also seems to be a "foo" exception in the login controller that may not have been intentionally left in.

**Comment by johnbender** [comment]
@dgreen 

The exception should be gone

https://github.com/johnbender/jqm-rails/commit/2a361e0cea59db5eb8cb8391be0d204fe126c831

And I added the one liner to the manual setup instructions. Please reopen if these don't address the issue.
